version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  groups:
    # Group all npm dependency updates into a single PR to reduce PR noise
    npm-dependencies:
      patterns:
        - "*"
- package-ecosystem: nuget
  directory: "/api/TweetBot"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  groups:
    # Group all nuget dependency updates into a single PR to reduce PR noise
    nuget-dependencies:
      patterns:
        - "*"
